export component IconButton inherits Rectangle {
    callback clicked <=> touch.clicked;

    in property <image> icon;
    property <color> icon_color:  touch.has-hover ? #ffffff : #94a3b8;
    height: 24px;
    width: 24px;
    background: transparent;
    touch := TouchArea {
        mouse-cursor: pointer;
    }

    Image {
        source: icon;
        colorize: icon_color;
        width: 24px;
        height: 24px;
    }
}
